// Mocks generated by Mockito 5.0.17 from annotations
// in solid_timer/test/src/bloc/solid_timer_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:solid_timer/src/domain/datasource/timer_repository.dart' as _i3;
import 'package:solid_timer/src/domain/models/timer.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTimer_0 extends _i1.Fake implements _i2.Timer {}

/// A class which mocks [TimerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerRepository extends _i1.Mock implements _i3.TimerRepository {
  MockTimerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Timer>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i2.Timer>>.value(<_i2.Timer>[]))
          as _i4.Future<List<_i2.Timer>>);
  @override
  _i4.Future<_i2.Timer> create({int? seconds}) =>
      (super.noSuchMethod(Invocation.method(#create, [], {#seconds: seconds}),
              returnValue: Future<_i2.Timer>.value(_FakeTimer_0()))
          as _i4.Future<_i2.Timer>);
  @override
  _i4.Future<void> deleteBy({int? id}) =>
      (super.noSuchMethod(Invocation.method(#deleteBy, [], {#id: id}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<_i2.Timer?> getLastSelectedTimer() =>
      (super.noSuchMethod(Invocation.method(#getLastSelectedTimer, []),
          returnValue: Future<_i2.Timer?>.value()) as _i4.Future<_i2.Timer?>);
}
